language: python
before_install:
  - git config --global user.name 'TravisCI'
  - git config --global user.email  $HOSTNAME":not-for-mail@travis-ci.org";
install: "pip install -r requirements.txt"
script: python setup.py test
python:
    - "2.7"
